#!/bin/sh

applications=(
    'iterm2-beta'
    'google-drive'
    'dropbox'
    'evernote'
    'firefox'
    'github'
    'google-chrome'
    'chromium'
    'mou'
    'mysqlworkbench'
    'opera'
    'sequel-pro'
    'sourcetree'
    'sublime-text3'
    'google-chrome-canary'
    'coda'
    'flash-player'
    'totalfinder'
    'yorufukurou'
    'xquartz'
    'java'
    'atom'
    'appcleaner'
    'caffeine'
    'flux'
    'font-source-code-pro'
    'gimp-lisanet'
    'gpgtools'
    'onyx'
    'the-unarchiver'
    'thunderbird'
    'transmission'
    'tunnelblick-beta'
    'vlc'
    'virtualbox'
    'vmware-fusion'
    'vagrant'
    'vessel'
)

brew tap phinze/homebrew-cask

for app in "${applications[@]}"
do
    echo "\n\n"
    echo "Installing $app..."
    brew cask install $app
done
